import asyncio
from playwright.async_api import async_playwright
import os

async def convert_to_pdf():
    md_file = 'GotLucky_Full_Conversation_Log.md'
    html_file = 'temp_log.html'
    pdf_file = 'GotLucky_Conversation_History.pdf'

    if not os.path.exists(md_file):
        print("Markdown file not found")
        return

    with open(md_file, 'r', encoding='utf-8') as f:
        content = f.read()

    # Simple Markdown to HTML conversion (or just wrap in pre)
    html_content = f"""
    <!DOCTYPE html>
    <html>
    <head>
        <meta charset="utf-8">
        <style>
            body {{ font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; line-height: 1.6; color: #333; max-width: 800px; margin: 40px auto; padding: 20px; }}
            h1 {{ color: #1a73e8; border-bottom: 2px solid #1a73e8; padding-bottom: 10px; }}
            h2 {{ color: #1e8e3e; margin-top: 30px; border-bottom: 1px solid #eee; }}
            h3 {{ color: #5f6368; }}
            blockquote {{ background: #f8f9fa; border-left: 5px solid #1a73e8; padding: 10px 20px; margin: 20px 0; font-style: italic; }}
            code {{ background: #f1f3f4; padding: 2px 4px; border-radius: 4px; font-family: Consolas, monospace; }}
            hr {{ border: 0; border-top: 1px solid #eee; margin: 40px 0; }}
            .footer {{ text-align: center; font-size: 0.8rem; color: #999; margin-top: 50px; }}
        </style>
    </head>
    <body>
        {content.replace('# ', '<h1>').replace('</h1>', '').replace('<h1>', '<h1>').replace('## ', '<h2>').replace('### ', '<h3>').replace('\n', '<br>')}
        <!-- This is a very crude parser, but let's try something better -->
    </body>
    </html>
    """
    
    # Better approach: use a minimal markdown rendering style
    import markdown
    try:
        html_body = markdown.markdown(content, extensions=['extra', 'codehilite'])
    except:
        # Fallback if markdown package isn't there
        html_body = content.replace('\n', '<br>')

    html_wrapped = f"""
    <!DOCTYPE html>
    <html>
    <head>
        <meta charset="utf-8">
        <style>
            body {{ font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif; line-height: 1.6; color: #202124; max-width: 900px; margin: 0 auto; padding: 50px; }}
            h1 {{ font-size: 2.5rem; color: #1a73e8; margin-bottom: 1rem; }}
            h2 {{ font-size: 1.8rem; color: #3c4043; margin-top: 2rem; border-bottom: 1px solid #dadce0; padding-bottom: 0.5rem; }}
            h3 {{ font-size: 1.3rem; color: #1e8e3e; margin-top: 1.5rem; }}
            p, li {{ font-size: 1rem; }}
            code {{ background: #f1f3f4; padding: 0.2rem 0.4rem; border-radius: 4px; font-family: "Roboto Mono", monospace; }}
            blockquote {{ border-left: 4px solid #1a73e8; background: #e8f0fe; padding: 1rem; margin: 1.5rem 0; border-radius: 0 8px 8px 0; }}
            ul {{ padding-left: 1.5rem; }}
            .header-info {{ font-size: 0.9rem; color: #70757a; margin-bottom: 3rem; }}
        </style>
    </head>
    <body>
        <div class="header-info">Generated by Antigravity AI Assistant</div>
        {html_body if 'html_body' in locals() else content.replace('\n', '<br>')}
    </body>
    </html>
    """

    with open(html_file, 'w', encoding='utf-8') as f:
        f.write(html_wrapped)

    async with async_playwright() as p:
        browser = await p.chromium.launch()
        page = await browser.new_page()
        # Use file URL
        abs_path = os.path.abspath(html_file)
        await page.goto(f'file:///{abs_path}')
        await page.pdf(path=pdf_file, format='A4', margin={'top': '2cm', 'bottom': '2cm', 'left': '2cm', 'right': '2cm'})
        await browser.close()
    
    os.remove(html_file)
    print(f"PDF generated: {pdf_file}")

if __name__ == "__main__":
    try:
        asyncio.run(convert_to_pdf())
    except Exception as e:
        print(f"Error: {e}")
